### ISSUE TITLE
Android: "Invalid url, go in settings" despite app working

### ISSUE THREAD

**Issue by dermesser** [publifactory/Overland_android#12]
Hey - thanks for making this app!

Sometimes it works even too well :-) I installed it from the play store today, and the start screen has an orange bar saying "Invalid url, go to settings" (probably from [here](https://github.com/OpenHumans/Overland_android/blob/1c31b4606411cb8182ce8a128158e24c492e949c/src/scenes/tracker/components/tracker-location-display/index.js#L21)).

The thing is: According to my server logs, the app is actually sending locations.

**Comment by dermesser** [comment]
I couldn't reproduce this on a second phone of mine, unfortunately. So maybe it is spurious. Let me know if you need more information about the OS etc. :)

**Comment by dshanske** [comment]
I get this sometimes when the network cuts out

**Comment by dermesser** [comment]
I see. that makes sense. Nevermind in that case :+1:

**Comment by gedankenstuecke** [comment]
Thanks @dermesser and @dshanske for reporting and letting us know! I know that for the iOS app similar issues can occur when there's some network cut issues. And let us know if there's a clearer pattern we can investigate :-)

**Comment by dshanske** [comment]
It should recognize unable to connect with a better error message
